### PR TITLE
CheriOS qemu

### PR DESCRIPTION
**Pull request by arichardson**
The CheriOS changes have been merge to QEMU, so we no longer need a
separate target.

Not merging directly since I don't have a setup to test CheriOS stuff right now.

### CODE REVIEW

**Comment by nwf** [comment]
This seems fine, but it means that the qemu binary is now in `${outroot}/sdk/bin` not `${outroot}/cherios-sdk/bin`.

**Comment by LawrenceEsswood** [comment]
Seems fine to me, when we get LLVM merged then cherios-sdk should die completely.

**Comment by LawrenceEsswood** [comment]
I should note only my branch of CheriOS will work with this, which won't become master until LLVM is merged. Maybe hold off committing this until then? Otherwise we might annoy people on master of CheriOS.Sent from my Samsung device

-------- Original message --------

**Comment by jrtc27** [comment]
@LawrenceEsswood What's the status of things? Does CheriOS master work with stock CHERI-QEMU these days?

**Comment by LawrenceEsswood** [comment]
LLVM merge went stale =/ Need to resurrect that and merge it first.

**Comment by jrtc27** [comment]
I don't understand why supporting QEMU is dependent on getting your LLVM merged into the main CHERI-LLVM. Can you not just fix your own LLVM to do whatever is needed for newer QEMU (not that I understand why that's even needed)?

**Comment by LawrenceEsswood** [comment]
I think I was holding off pointing CheriOS to a new LLVM /(and updating it to my branch) until it could be pointed at CHERI-LLVM. I think its achievable if this branch needs killing off urgently, but it is not currently on the list.

**Comment by LawrenceEsswood** [comment]
Actually, now I'm just massively confused on what the working state was. I really should go back and get CheriOS sorted.

**Comment by jrtc27** [comment]
It's not urgent, I was just having a look through old issues and PRs for cheribuild trying to clean things up.

**Comment by arichardson** [comment]
Superseded by #253.

**Pull request closed without merging**
