### PR TITLE
Allow us to build minimal images for Morello

### PR DESCRIPTION
**Pull request by zxombie**

### CODE REVIEW

**Comment by jrtc27** [comment]
Should include aarch64 for completeness

**Comment by jrtc27** [comment]
Or maybe at this point we just support the same set of architectures as CheriBSD rather than repeating the list?...

**Comment by zxombie** [comment]
I tried adding `MORELLO_NO_CHERI`, but got:
```
LookupError: Could not find 'cheribsd' target for CheriBSDMorelloTargetInfo(AARCH64), caller was <pycheribuild.projects.disk_image.BuildMinimalCheriBSDDiskImage_
CheriBSD-Morello-morello-purecap object at 0x8017b6fd0>
```

**Comment by jrtc27** [comment]
That's because it's called AArch64.

**Comment by arichardson** [comment]
> > Or maybe at this point we just support the same set of architectures as CheriBSD rather than repeating the list?...
> 
> @arichardson thoughts?

Yes that would make sense. I think the only reason that the lists are different is that cheribsdbox was only supported for MIPS initially.

**Review by arichardson — APPROVED** [review]
This looks fine to me, we can merge the lists in a follow-up commit.

**Pull request merged**
