### PR TITLE
Allow compiling kernel modules on RISC-V.

### PR DESCRIPTION
**Pull request by bsdjhb**
While here, move a comment about the malo module failure to the right
place.

### CODE REVIEW

**Comment by bsdjhb** [comment]
Individual kernel configs can still opt out of modules via makeoptions.

**Comment by jrtc27** [comment]
Out of interest, have you tried letting it build malo? It's possible this bug has inadvertently been fixed or no longer gets triggered after the two most recent upstream LLVM merges.

**Comment by bsdjhb** [comment]
I can try that easily enough

**Comment by bsdjhb** [comment]
I haven't tried building malo with the master branch btw, do we want to wait to push that until we update LLVM master?  (When are we next planning on updating CheriBSD and LLVM master anyway?)

**Comment by arichardson** [comment]
I'd be happy to merge LLVM any time but it needs a cheribsd merge first.

**Comment by brooksdavis** [comment]
I'm working on a CheriBSD merge now (currently verifying that LLVM master builds CheriBSD dev)

**Comment by bsdjhb** [comment]
I think brooks merged CheriBSD so that leaves an llvm merge to 'master' as a dependency of this I think?

**Comment by arichardson** [comment]
I've just merged LLVM dev to master, so will merge this on Monday to give people time to rebuild LLVM.

**Comment by bsdjhb** [comment]
Ok to merge this now?

**Pull request merged**
